spring.application.name=RentalCar
server.port=9191

square.access.token=EAAAl0zc3fgVaO2CQ_dQy_wfwIp8OcWUmVgGxk85o5E0H9wG82343Zcn5UQQ_x9L
square.location.id=LPZRXZDYDTHVZ
square.environment=SANDBOX


spring.datasource.url=jdbc:mysql://localhost:3306/rentalcar_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-request-size=10MB
##(create, update, create-drop, validate)
spring.jpa.hibernate.ddl-auto=update
